config/routes.rb
Rails.application.routes.draw do

  resources :accepted_jobs
  resources :asking_prices
  resources :skills
  resources :job_postings
  resources :payment_informations
  
  resources :users
  resources :sessions
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'home', to: 'home#home', as: :home
  get 'dashboard', to: 'home#index', as: :dashboard
  get 'buy', to: 'job_postings#new', :as => :buy
  get 'sell', to: 'asking_prices#new', :as => :sell

  get 'initiate_job_buy/:jp_id' => 'accepted_jobs#initiate_buy', as: :initiate_job_buy
  get 'initiate_job_sell/:ap_id' => 'accepted_jobs#initiate_sell', as: :initiate_job_sell
  get 'make_accepted_job/:jp_id/:ap_id' => 'accepted_jobs#make', as: :make_accepted_job

  get 'review_provider/:aj_id' => 'accepted_jobs#review_provider', as: :review_provider
  post 'review_update_provider/:aj_id/' => 'accepted_jobs#review_update_provider', as: :review_update_provider
  get 'review_client/:aj_id' => 'accepted_jobs#review_client', as: :review_client
  post 'review_update_client/:aj_id/' => 'accepted_jobs#review_update_client', as: :review_update_client

  get 'buyer_complete/:aj_id' => 'accepted_jobs#buyer_complete', as: :buyer_complete
  get 'seller_complete/:aj_id' => 'accepted_jobs#seller_complete', as: :seller_complete

  get 'completed_jobs' => 'accepted_jobs#completed_jobs', as: :completed_jobs
  get 'active_jobs' => 'accepted_jobs#active_jobs', as: :active_jobs

  get 'user_reviews/:u_id' => 'users#user_reviews', as: :user_reviews

  get "/pages/:page" => "pages#show"

  root :to => 'home#home'
  

end

app/views/partials/_footer.html.erb
<footer id= "footer">
	<%= link_to 'Home', home_path %>	&nbsp;&nbsp;::&nbsp;&nbsp;
	<a href="/pages/faq">FAQ</a> &nbsp;&nbsp;::&nbsp;&nbsp;	
	<a href="/pages/about">About Us</a> &nbsp;&nbsp;::&nbsp;&nbsp;
	<a href="/pages/contact">Contact Us</a> &nbsp;&nbsp;::&nbsp;&nbsp;
	<a href="/pages/terms">Terms of Service</a> &nbsp;&nbsp;::&nbsp;&nbsp;
	<a href="/pages/privacy">Privacy Policy</a> &nbsp;&nbsp;::&nbsp;&nbsp;
	<a href="/pages/careers">Careers</a> &nbsp;&nbsp;::&nbsp;&nbsp;
	<br>
	<div id="copy">
		<p>	Webmaster: <%= mail_to("example@example.gov", "Campus Connect Administration", encode: "javascript") %> 
		&nbsp;&nbsp;&copy 2016 </p>
	</div>
</footer>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home" style="width: 60%;">
        <span>Campus Connect</span>
        <div style="margin-top: -5px;float: left;font-size:10px;"> Stop Waiting. Start Doing.</div> 
      </a>
    </div>

  

<!-- Collect the nav links, forms, and other content for toggling -->
<!-- Left Navigation Options -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class= "active"><a href="/dashboard">Marketplace</a></li> <span class="sr-only">(current)</span></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> New Jobs/Services <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Seek Services', buy_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Offer Services', sell_path %></li>
            <li><%= link_to 'View Open Jobs', job_postings_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Add Skill', new_skill_path %></li>
          </ul>
        </li>
      </ul>

<!-- Search Bar -->
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

<!-- Right Navigation Options --> 
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/pages/faq">Rules</a></li>
        <% if !logged_in? %>
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to "Sign Up", signup_path %></li>
        <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href=<%=user_path(current_user) %>>Your Profile</a></li>
            <li><%= link_to("Active Jobs",active_jobs_path) %></li>
            <li><%= link_to("View Job History",completed_jobs_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Logout', logout_path %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>