config/routes.rb
Rails.application.routes.draw do

  resources :accepted_jobs
  resources :asking_prices
  resources :skills
  resources :job_postings
  resources :payment_informations
  
  resources :users
  resources :sessions
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'home', to: 'home#home', as: :home
  get 'dashboard', to: 'home#index', as: :dashboard
  get 'buy', to: 'job_postings#new', :as => :buy
  get 'sell', to: 'asking_prices#new', :as => :sell

  get 'initiate_job_buy/:jp_id' => 'accepted_jobs#initiate_buy', as: :initiate_job_buy
  get 'initiate_job_sell/:ap_id' => 'accepted_jobs#initiate_sell', as: :initiate_job_sell
  get 'make_accepted_job/:jp_id/:ap_id' => 'accepted_jobs#make', as: :make_accepted_job

  get 'review_provider/:aj_id' => 'accepted_jobs#review_provider', as: :review_provider
  post 'review_update_provider/:aj_id/' => 'accepted_jobs#review_update_provider', as: :review_update_provider
  get 'review_client/:aj_id' => 'accepted_jobs#review_client', as: :review_client
  post 'review_update_client/:aj_id/' => 'accepted_jobs#review_update_client', as: :review_update_client

  get 'buyer_complete/:aj_id' => 'accepted_jobs#buyer_complete', as: :buyer_complete
  get 'seller_complete/:aj_id' => 'accepted_jobs#seller_complete', as: :seller_complete

  get 'completed_jobs' => 'accepted_jobs#completed_jobs', as: :completed_jobs
  get 'active_jobs' => 'accepted_jobs#active_jobs', as: :active_jobs

  get 'user_reviews/:u_id' => 'users#user_reviews', as: :user_reviews

  get "/pages/:page" => "pages#show"

  root :to => 'home#home'
  

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  password_digest :string
#  role            :string
#  first_name      :string
#  last_name       :string
#  phone           :string
#  email           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  active          :boolean
#  buyer_bio       :text
#  seller_bio      :text
#

class User < ActiveRecord::Base

  #Use built-in rails support for password protection
  has_secure_password
  
  #Relationship Validations
  has_many :job_postings
  has_many :skills
  
  #Validations
  # Validations
  validates_presence_of :last_name, :first_name, :email, :phone
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, message: "is not a valid format"
  validates_format_of :phone, with: /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, message: "should be 10 digits (area code needed) and delimited with dashes only"
  validates :username, presence: true, uniqueness: { case_sensitive: false}
  validates_presence_of :password, on: :create 
  validates_presence_of :password_confirmation, on: :create 
  validates_confirmation_of :password, on: :create, message: "does not match"
  validates_length_of :password, minimum: 4, message: "must be at least 4 characters long", allow_blank: true

  ROLES = [['Administrator', :admin], ['Buyer', :buyer], ['Seller', :seller], ['Buyer/Seller', :bser]]
  PROLES = [['Buyer', :buyer], ['Seller', :seller], ['Buyer/Seller', :bser]]

  #Methods
  def self.authenticate(username,password)
    find_by_username(username).try(:authenticate, password)
  end

  def name
    self.first_name + " " + self.last_name
  end

  def average_buyer_rating
    jps = self.job_postings
    buy_rats = []
    jps.each do |jp|
      if (not(jp.accepted_job.nil?) and not(jp.accepted_job.buyer_rating.nil?))
        buy_rats.append(jp.accepted_job.buyer_rating)
      end
    end
    res = buy_rats.inject(:+).to_f / buy_rats.length
    res.nan? ? "No Ratings Yet" : res
  end

  def average_seller_rating
    jps = self.seller_accepted_jobs.map{|j| j.seller_rating}
    # sell_rats = []
    # jps.each do |jp|
      # if (not(jp.accepted_job.nil?) and not(jp.accepted_job.seller_rating.nil?))
    #     sell_rats.append(jp.accepted_job.seller_rating)
    #   end
    # end
    jps = jps.inject(:+).to_f / jps.length
    jps.nan? ? "No Ratings Yet" : jps
  end

  # def average_seller_rating
  #   jps = self.buyer_accepted_jobs
  #   sell_rats = []
  #   jps.each do |jp|
  #     if (not(jp.accepted_job.nil?) and not(jp.accepted_job.seller_rating.nil?))
  #       sell_rats.append(jp.accepted_job.seller_rating)
  #     end
  #   end
  #   res = sell_rats.inject(:+).to_f / sell_rats.length
  #   res.nan? ? "No Ratings Yet" : res
  # end

  def seller_accepted_jobs
    self.skills.to_a.map{|s| s.asking_prices.to_a.map{|ap| ap.accepted_jobs.to_a}}.flatten.compact
  end

  def buyer_accepted_jobs
    self.job_postings.to_a.map{|jp| jp.accepted_job}.flatten.compact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.paginate(:page => params[:page]).per_page(10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    # respond_to do |format|
    #   if @user.update(user_params)
    #     format.html { redirect_to home_path, notice: 'User was successfully updated.' }
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: 'edit' }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.active = true
    # @buyer = Buyer.new
    # @seller = Seller.new

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        # @buyer.user_id = @user.id
        # @buyer.save
        # @seller.user_id = @user.id
        # @seller.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def user_reviews
    @user = User.find(params[:u_id])
    @saj = @user.seller_accepted_jobs
    @baj = @user.buyer_accepted_jobs
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:id,:user,:username, :password, :password_confirmation, :role, :first_name,
      :last_name, :phone, :email, :buyer_bio, :seller_bio, :user_bio)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> need to be addressed in order to create an account:</h2>
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <center>
    <TABLE class="table" style="width:400px">
      <% if controller.action_name=="create" || controller.action_name=="new"%>
      <TR><TD>
            <%= f.label :username %><br>
            <%= f.hint 'No special characters, please!' %>
          </TD><TD>
            <%= f.input_field :username %>
            <%= f.error :username, id: 'user_name_error' %>
          </TD>
      </TR>
      <TR><TD>
            <%= f.label :password %><br>
            <%= f.hint 'Cannot be less than 4 characters.' %>
          </TD><TD>
            <%= f.input_field :password %>
            <%= f.error :password, id: 'password_error' %>
          </TD>
      </TR>
      <TR><TD>
           <%= f.label :password_confirmation %>
            <%= f.hint 'Must match password entered.' %>
          </TD><TD>
            <%= f.input_field :password_confirmation %>
            <%= f.error :password_confirmation, id: 'password_confirmation_error' %>
          </TD>
      </TR>
      <% end %>
      
      <TR><TD>
        <%= f.label :first_name %>
        <%= f.hint 'Please put your name' %>
      </TD><TD>
        <%= f.input_field :first_name %>
        <%= f.error :first_name, id: 'first_name_error' %>
      </TD>
      </TR>
      <TR><TD>
    <%= f.label :last_name %>
    <%= f.hint 'Names help make transactions easier.' %>
      </TD><TD>
    <%= f.input_field :last_name %>
    <%= f.error :last_name, id: 'last_name_error' %>
      </TD>
      <TR><TD>
    <%= f.label :email %>
    <%= f.hint 'Primary method of communicating with others/receiving notifications.' %>
      </TD><TD>
    <%= f.input_field :email, placeholder: "example@email.com" %>
    <%= f.error :email, id: 'email_error' %>
      </TD>
      <TR><TD>
    <%= f.label :phone %>
        <%= f.hint 'Allows for text notifications and alternative contact methods.' %>

      </TD><TD>
    <%= f.input_field :phone, placeholder: "999-999-9999" %>
    <%= f.error :phone, id: 'phone_error' %>
      </TD>
      </TR>

      <TR><TD>
    <%= f.label :about %>
        <%= f.hint 'Optional.' %>

      </TD><TD>
    <%= f.input_field :seller_bio, placeholder: "" %>
    <%= f.error :seller_bio, id: 'seller_bio error' %>
      </TD>
      </TR>

    </TABLE>
    </center>
  </div>
  
  <% if controller.action_name=="create" || controller.action_name=="new"%>

  <br>
  <div class="checkbox">
        <label>
            <input type="checkbox"> <p> I agree to the <a href="/pages/terms" target="_blank">terms and conditions</a> and <a href="/pages/privacy" target="_blank"> privacy policy. </p> </a>  
        </label>
  </div> 
  
  <div class="checkbox">
        <label>
            <input type="checkbox"> <p> I agree not to use this service in a manner that violates academic integrity guidelines explained <a href="/pages/faq" target="_blank">here. </p> </a>
        </label>
  </div> 
  <% end %>
  
  <br>
  <center>
  <div class="actions">
  <% if controller.action_name=="create" || controller.action_name=="new"%>
    <%= f.button :submit, "Create Account", class: "btn btn-success"%> <br>
  <% else %>
    <%= f.button :submit, "Edit Profile", class: "btn btn-success"%> <br>
  <% end %> 
  </div>
  </center>

<% end %>

app/views/users/edit.html.erb
<div class="container"> 
    <div class="row centered-form">
        <div class="col-xs-12 col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
            <div class="card card-container">
            <div class="well">
            <center>
            <h1>Editing User</h1>
            </center>
            <%= render 'form' %>
            <center> <br>
            <!--<%= link_to 'View Profile', @user, class: "btn btn-info" %> |-->
            <%= link_to 'Cancel', @user, class: "btn btn-danger" %>
            </center>
            </div>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div class="col-xs-12 col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
<h1>User Ratings</h1>
<div class="dropdown">
  <button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Sort
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dLabel">
    <li><a href="#">Highest Rated (Buyer)</a></li>
    <li><a href="#">Lowest Rated (Buyer)</a></li>
    <li><a href="#">Highest Rated (Seller)</a></li>
    <li><a href="#">Lowest Rated (Seller)</a></li>
  </ul>
</div>
<table class="table">
  <thead>
    <tr>
      <th><p>Username</p></th>
      <!-- <th>Password digest</th> -->
      <!-- <th>Role</th> -->
     <!--  <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Email</th> -->
      <th><p>Average Buyer Rating</p></th>
      <th><p>Average Seller Rating</p></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><p><%= link_to user.username, user_reviews_path(user) %></p></td>
        <!-- <td><%= user.password_digest %></td> -->
        <!-- <td><%= user.role %></td> -->
        <!-- <td><% user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td> -->
        <td><p><%= user.average_buyer_rating %></p></td>
        <td><p><%= user.average_seller_rating %></p></td>
        <% if logged_in? and current_user.role == "admin" %>
          <td><%= link_to 'Show', user %></td>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
<%# link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container"> 
    <div class="row centered-form">
        <div class="col-xs-12 col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
            <div class="card card-container">
            <div class="well">
            <center>
            <h1>Create An Account</h1>
            <p style="font-size:12px;"> <i> * Marks Required Fields </i> </p>
            </center>
            <%= render 'form' %>
            <br>
            <center>
            <%= link_to 'Cancel', home_path, class: "btn btn-danger" %>
            </center>
            </div>
            </div>
        </div>
    </div>
</div>
<br><br>

app/views/users/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<%= stylesheet_link_tag "user_show.css" %>

<div class="container">
	<div class="row">
		<div class="col-md-offset-1 col-md-10 col-lg-offset-1 col-lg-10">
    	 <div class="well profile">
            <div class="col-sm-12">
                <div class="col-xs-12 col-sm-8">
                    <h2><%=@user.first_name%> <%=@user.last_name%></h2>
                    <p><strong>Bio: </strong> <%= @user.seller_bio %> </p>
                    <p><strong>Hobbies: </strong> Read, out with friends, listen to music, draw and learn new things. </p>
                    <p><strong>Skills: </strong>
                    <% current_user.skills.each do |skill| %>
                      <span class="tags"><%=skill.skill %></span>   
                    <% end %>
                        <span class="btn btn-default noselect"><%= link_to 'Add Skill', new_skill_path %></span>
                    </p>
                </div>             
                <div class="col-xs-12 col-sm-4 text-center">
                    <figure>
                        <img src=<%=image_path "bearded-man.jpg"%> alt="" class="img-circle img-responsive">
                        <figcaption class="ratings">
                            <p>Ratings
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                            <a href="#">
                                 <span class="fa fa-star-o"></span>
                            </a> 
                            </p>
                        </figcaption>
                    </figure>
                </div>
            </div>            
            <div class="col-xs-12 divider text-center">
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong> 20.7K </strong></h2>                    
                    <p><small>Followers</small></p>
                    <button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Follow </button>
                </div>
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong>245</strong></h2>                    
                    <p><small>Following</small></p>
                    <!--<button class="btn btn-info btn-block"><span class="fa fa-user"></span> View Profile </button>-->
                </div>
                <div class="col-xs-12 col-sm-4 emphasis">
                    <h2><strong>43</strong></h2>                    
                    <p><small>Snippets</small></p>
                    <!--<button class="btn btn-info btn-block"><span class="fa fa-user"></span> View Profile </button>-->
                    <a href="<%= edit_user_path(current_user) %>">
                      <button type="button" class="btn btn-info btn-block">
                        <span class="fa fa-gear"></span>Edit
                      </button>
                    </a>

                    <!--<div class="btn-group dropup btn-block">-->
                    <!--  <button type="button" class="btn btn-primary"><span class="fa fa-gear"></span> Options </button>-->
                    <!--  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">-->
                    <!--    <span class="caret"></span>-->
                    <!--    <span class="sr-only">Toggle Dropdown</span>-->
                    <!--  </button>-->
                    <!--  <ul class="dropdown-menu text-left" role="menu">-->
                    <!--    <li><a href="#"><span class="fa fa-envelope pull-right"></span> Send an email </a></li>-->
                    <!--    <li><a href="#"><span class="fa fa-list pull-right"></span> Add or remove from a list  </a></li>-->
                    <!--    <li class="divider"></li>-->
                    <!--    <li><a href="#"><span class="fa fa-warning pull-right"></span>Report this user for spam</a></li>-->
                    <!--    <li class="divider"></li>-->
                    <!--    <li><a href="#" class="btn disabled" role="button"> Unfollow </a></li>-->
                    <!--  </ul>-->
                    <!--</div>-->
                </div>
            </div>
    	 </div>                 
		</div>
	</div>
</div>


<br><br><br><br><br>

app/views/users/user_reviews.html.erb
<div class="col-xs-12 col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
<center>
<h2><%= "Reviews for " + @user.username %></h2>
<p id="notice"><%= notice %></p>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#buyrev" aria-controls="home" role="tab" data-toggle="tab"><p><b>Reviews as a Buyer of Services</b></p></a></li>
    <li role="presentation"><a href="#sellrev" aria-controls="profile" role="tab" data-toggle="tab"><p><b>Reviews as a Seller of Services</b></p></a></li>
  </ul>

  </center>
    <div class="dropdown">
  <button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Sort
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dLabel">
    <li><a href="#">Highest Rating</a></li>
    <li><a href="#">Lowest Rating</a></li>
  </ul>
</div>
<center>

  <!-- Tab panes -->
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="buyrev">

  <table class="table">
    <thead>
      <tr>
        <!-- <th>Sell</th> -->
        <!-- <th>Skill</th> -->
        <th><p>Job</p></th>
        <!-- <th><p>Description</p></th> -->
        <th><p>Rating</p></th>
        <th><p>Review</p></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @baj.each do |aj| %>
        <tr>
          <!-- <td><%# asking_price.seller_id %></td> -->
          <!-- <td><%# asking_price.skill_id %></td> -->
          <td><p><%= aj.job_posting.job_name %></p></td>
          <!-- <td><p><%# asking_price.skill.description %></p></td> -->
          <td><p><%= aj.buyer_rating.nil? ? "Not Yet Rated" : aj.buyer_rating.to_f %></p></td>
          <td><p><%= aj.buyer_review.nil? ? "Not Yet Reviwed" : aj.buyer_review %></p></td>
          <!-- <td><%# link_to 'Initiate Job', initiate_job_sell_path(asking_price), class: "btn btn-success" %></td>
          <td><%# link_to 'Edit', edit_asking_price_path(asking_price), class: "btn btn-warning"%></td>
          <td><%# link_to 'Delete', asking_price, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure you want to delete this job offering?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>

  </div>

  <div role="tabpanel" class="tab-pane" id="sellrev">

  <table class="table">
    <thead>
      <tr>
        <!-- <th>Sell</th> -->
        <!-- <th>Skill</th> -->
        <th><p>Job</p></th>
        <!-- <th><p>Description</p></th> -->
        <th><p>Rating</p></th>
        <th><p>Review</p></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @saj.each do |aj| %>
        <tr>
          <!-- <td><%# asking_price.seller_id %></td> -->
          <!-- <td><%# asking_price.skill_id %></td> -->
          <td><p><%= aj.job_posting.job_name %></p></td>
          <!-- <td><p><%# asking_price.skill.description %></p></td> -->
          <td><p><%= aj.seller_rating.nil? ? "Not Yet Rated" : aj.seller_rating.to_f %></p></td>
          <td><p><%= aj.seller_review.nil? ? "Not Yet Reviwed" : aj.seller_review %></p></td>
          <!-- <td><%# link_to 'Initiate Job', initiate_job_sell_path(asking_price), class: "btn btn-success" %></td>
          <td><%# link_to 'Edit', edit_asking_price_path(asking_price), class: "btn btn-warning"%></td>
          <td><%# link_to 'Delete', asking_price, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure you want to delete this job offering?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  </div>
</div>