config/routes.rb
Rails.application.routes.draw do

  resources :accepted_jobs
  resources :asking_prices
  resources :skills
  resources :job_postings
  resources :payment_informations
  
  resources :users
  resources :sessions
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'home', to: 'home#home', as: :home
  get 'dashboard', to: 'home#index', as: :dashboard
  get 'buy', to: 'job_postings#new', :as => :buy
  get 'sell', to: 'asking_prices#new', :as => :sell

  get 'initiate_job_buy/:jp_id' => 'accepted_jobs#initiate_buy', as: :initiate_job_buy
  get 'initiate_job_sell/:ap_id' => 'accepted_jobs#initiate_sell', as: :initiate_job_sell
  get 'make_accepted_job/:jp_id/:ap_id' => 'accepted_jobs#make', as: :make_accepted_job

  get 'review_provider/:aj_id' => 'accepted_jobs#review_provider', as: :review_provider
  post 'review_update_provider/:aj_id/' => 'accepted_jobs#review_update_provider', as: :review_update_provider
  get 'review_client/:aj_id' => 'accepted_jobs#review_client', as: :review_client
  post 'review_update_client/:aj_id/' => 'accepted_jobs#review_update_client', as: :review_update_client

  get 'buyer_complete/:aj_id' => 'accepted_jobs#buyer_complete', as: :buyer_complete
  get 'seller_complete/:aj_id' => 'accepted_jobs#seller_complete', as: :seller_complete

  get 'completed_jobs' => 'accepted_jobs#completed_jobs', as: :completed_jobs
  get 'active_jobs' => 'accepted_jobs#active_jobs', as: :active_jobs

  get 'user_reviews/:u_id' => 'users#user_reviews', as: :user_reviews

  get "/pages/:page" => "pages#show"

  root :to => 'home#home'
  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def home
    @app_page="Home"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.erb
<% content_for :footer do %>
    <footer>
         <section id="contact" class="contact bg-primary">
        <div class="container">
            <h2><i class="fa fa-heart"></i> Connect with us</h2>
            <ul class="list-inline list-social">
                <li class="social-twitter">
                    <a href="#"><i class="fa fa-twitter"></i></a>
                </li>
                <li class="social-facebook">
                    <a href="#"><i class="fa fa-facebook"></i></a>
                </li>
                <li class="social-google-plus">
                    <a href="#"><i class="fa fa-google-plus"></i></a>
                </li>
                    <li class="">
                    <a href="#"><img src="<%=image_path "tinder-icon.png" %>" width=60 height=60 /></a>
                </li>
            </ul>
        </div>
    </section>

        <div class="container">
            <p>&copy; 2016 CampusConnect. Only Two Rights Reserved.</p>
            <ul class="list-inline">
                <li>
                    <a href="/pages/privacy">Privacy</a>
                </li>
                <li>
                    <a href="/pages/terms">Terms</a>
                </li>
                <li>
                    <a href="/pages/faq">FAQ</a>
                </li>
            </ul>
        </div>
    </footer>

   
    <!-- Theme JavaScript -->
    <script src=<%= javascript_path "new-age.js"%> ></script>
<% end %>



<!-- started /w code from https://raw.githubusercontent.com/BlackrockDigital/startbootstrap-new-age/master/index.html-->
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CampusConnect</title>



    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

    <!-- Plugin CSS -->
    <!--<link rel="stylesheet" href=<%#= stylesheet_path "font-awesome.min.css"%>>-->
    <!--<link rel="stylesheet" href=<%#= stylesheet_path "simple-line-icons.css" %>>-->
    <!--<link rel="stylesheet" href=<%#= stylesheet_path "device-mockups.min.css" %>>-->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">
    <video poster="https://upload.wikimedia.org/wikipedia/commons/6/67/Inside_the_Batad_rice_terraces.jpg" id="bgvid" playsinline autoplay muted loop>
      <!-- WCAG general accessibility recommendation is that media such as background video play through only once. Loop turned on for the purposes of illustration; if removed, the end of the video will fade in the same way created by pressing the "Pause" button  -->
        <source src=<%=asset_path "peeps.mp4"%> type="video/mp4"/>
    </video>
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <!--<a class="navbar-brand page-scroll" href="/dashboard">CampusConnect</a>-->
                <a class="navbar-brand page-scroll" style="font-size:20px;">CampusConnect</a>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <% if !logged_in? %>
                    <li>
                        <a class="page-scroll" href=<%=login_path%>>Login</a>
                    </li> 
                    <% else %>
                    <li>
                        <a class="page-scroll" href=<%=dashboard_path%>>Marketplace</a>
                    </li>
                    <% end %>
                    <li>
                        <a class="page-scroll" href="#download">Download</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#features">Features</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="container">
            <div class="row">
                <div class="col-md-5"></div>
                <div class="col-md-7">
                    <div class="header-content">
                        <div id="polina" class="header-content-inner">
                            <center>
                                <h1>The app to showcase your skills and buy services from others!</h1>
                            
                                <% if logged_in? %>
                                    <%= link_to "Start Now for Free!", dashboard_path, :class => "btn btn-outline btn-xl page-scroll" %>
                                <% else %>
                                    <%= link_to "Start Now for Free!", signup_path, :class => "btn btn-outline btn-xl page-scroll" %>
                                <% end %>
                            </center>
                        </div>
                    </div>
                </div>
                <!--<div class="col-sm-5">-->
                <!--    <div class="device-container">-->
                <!--        <div class="device-mockup iphone6_plus portrait white">-->
                <!--            <div class="device">-->
                <!--                <div class="screen">-->
                                    <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                                    <!--<img src=<%= image_path "demo-screen-1.jpg" %> class="img-responsive" alt="">-->
                <!--                </div>-->
                <!--                <div class="button">-->
                                    <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                <!--                </div>-->
                <!--            </div>-->
                <!--        </div>-->
                <!--    </div>-->
                <!--</div>-->
            </div>
        </div>
    </header>

    <section id="download" class="download bg-primary text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h2 class="section-heading">Enhance Your Productivity or Make Some Money</h2>
                    <p>Our app is available on desktop any mobile device! Download now or <a href="/signup" >Sign Up.</a></p>
                    <br>
                    <div class="badges">
                        <a class="badge-link" href="#"><img src=<%= image_path "google-play-badge.svg" %> alt=""></a>
                        <a class="badge-link" href="#"><img src=<%= image_path "app-store-badge.svg" %> alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="features" class="features">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="section-heading">
                        <h2>Post Jobs to be Done, Post Skills to Offer.</h2>
                        <p class="text-muted">Check out how easy it is to make money or get work done!</p>
                        <hr>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <!--<div class="device-container">-->
                    <!--    <div class="device-mockup iphone6_plus portrait white">-->
                    <!--        <div class="device">-->
                    <!--            <div class="screen">-->
                                    <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                                    <!--<img src=<%= image_path "demo-screen-1.jpg" %> class="img-responsive" alt=""> </div>-->
                    <!--                <i class="fa fa-check-circle" aria-hidden="true"></i>-->

                    <!--                &nbsp;-->
                                
                    <!--            <div class="button">-->
                                    <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                    <!--            </div>-->
                    <!--        </div>-->
                    <!--    </div>-->
                    </div>
                </div>
                
                <div class="col-md-12">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="feature-item">
                                    <i class="icon-screen-smartphone text-primary"></i>
                                    <h3>iOS/Android</h3>
                                    <p class="text-muted">Ready to use on any device!</p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="feature-item">
                                    <i class="icon-camera text-primary"></i>
                                    <h3>Any Skill</h3>
                                    <p class="text-muted">Post any skill, from photography to underwater basketweaving</p>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="feature-item">
                                    <i class="icon-present text-primary"></i>
                                    <h3>Free to Use</h3>
                                    <p class="text-muted">Sign up is free. We never sell your information to third parties.</p>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="feature-item">
                                    <i class="icon-lock-open text-primary"></i>
                                    <h3>Open Source</h3>
                                    <p class="text-muted">Sell your services or post your jobs to campus and the community!</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </section>

    <section class="cta">
        <div class="cta-content">
            <div class="container">
                <h2>Stop waiting<br>Start doing</h2>
                <% if logged_in? %>
                    <%= link_to "Let's Get Started!", dashboard_path, :class => "btn btn-outline btn-xl page-scroll" %>
                <% else %>
                    <%= link_to "Let's Get Started!", signup_path, :class => "btn btn-outline btn-xl page-scroll" %>
                <% end %>
            </div>
        </div>
        <div class="overlay"></div>
    </section>
</body>
</html>

app/views/home/index.html.erb
<div id="container" class="well">
  <center>
    <h1>Welcome to your Campus Connect Dashboard</h1>
    <!-- <h3>(still in development...)</h3> -->
    <div class="row">
      <div class="col-sm-3">
      </div>
      <div class="card">
        <div class="col-sm-3" id="getjob">
          <h4>Acquire or Provide a Job</h4>
          <br>
          <div id='jobs'>
              <%= link_to 'View Unfulfilled Jobs', job_postings_path, class: "btn btn-primary" %>
          </div>
          <br><br>
          <div id='skills'>
              <%= link_to 'View Jobs Offerings', asking_prices_path, class: "btn btn-primary" %>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="col-sm-3" id="buysell">
          <h4>View Accepted Jobs and Ratings</h4>
          <br>
          <% if logged_in? %>
            <div id='accepted'>
                <%= link_to 'View Accepted Jobs', accepted_jobs_path, class: "btn btn-info" %>
            </div>
            <br><br>
          <% end %>
          <div id='users'>
              <%= link_to 'View User Ratings', users_path, class: "btn btn-info" %>
          </div>
        </div>
      </div>
    </div>
  </center>
</div>