config/routes.rb
Rails.application.routes.draw do

  resources :accepted_jobs
  resources :asking_prices
  resources :skills
  resources :job_postings
  resources :payment_informations
  
  resources :users
  resources :sessions
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  get 'home', to: 'home#home', as: :home
  get 'dashboard', to: 'home#index', as: :dashboard
  get 'buy', to: 'job_postings#new', :as => :buy
  get 'sell', to: 'asking_prices#new', :as => :sell

  get 'initiate_job_buy/:jp_id' => 'accepted_jobs#initiate_buy', as: :initiate_job_buy
  get 'initiate_job_sell/:ap_id' => 'accepted_jobs#initiate_sell', as: :initiate_job_sell
  get 'make_accepted_job/:jp_id/:ap_id' => 'accepted_jobs#make', as: :make_accepted_job

  get 'review_provider/:aj_id' => 'accepted_jobs#review_provider', as: :review_provider
  post 'review_update_provider/:aj_id/' => 'accepted_jobs#review_update_provider', as: :review_update_provider
  get 'review_client/:aj_id' => 'accepted_jobs#review_client', as: :review_client
  post 'review_update_client/:aj_id/' => 'accepted_jobs#review_update_client', as: :review_update_client

  get 'buyer_complete/:aj_id' => 'accepted_jobs#buyer_complete', as: :buyer_complete
  get 'seller_complete/:aj_id' => 'accepted_jobs#seller_complete', as: :seller_complete

  get 'completed_jobs' => 'accepted_jobs#completed_jobs', as: :completed_jobs
  get 'active_jobs' => 'accepted_jobs#active_jobs', as: :active_jobs

  get 'user_reviews/:u_id' => 'users#user_reviews', as: :user_reviews

  get "/pages/:page" => "pages#show"

  root :to => 'home#home'
  

end

app/models/accepted_job.rb
# == Schema Information
#
# Table name: accepted_jobs
#
#  id               :integer          not null, primary key
#  job_posting_id   :integer
#  asking_price_id  :integer
#  seller_review    :text
#  buyer_review     :text
#  seller_rating    :integer
#  buyer_rating     :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  buyer_completed  :boolean
#  seller_completed :boolean
#

class AcceptedJob < ActiveRecord::Base

  #Relationship Validations
  belongs_to :asking_price
  belongs_to :job_posting

  #Scopes
  # scope :open_not_for_user, ->(uid) { joins("left outer join accepted_jobs on job_postings.id = accepted_jobs.job_posting_id").where("job_postings.user_id != ? and accepted_jobs.id IS NULL", uid) }
  scope :for_user_buyer, -> (uid) {joins(:job_posting => :user).where("users.id = ?", uid)}
  scope :for_user_seller, -> (uid) {joins(:asking_price => {:skill => :user}).where("users.id = ?", uid)}
  scope :comp_for_user_buyer, -> (uid) {joins(:job_posting => :user).where("(users.id = ?)", uid).where(buyer_completed: true).where(seller_completed: true)}
  scope :comp_for_user_seller, -> (uid) {joins(:asking_price => {:skill => :user}).where("(users.id = ?)", uid).where(buyer_completed: true).where(seller_completed: true)}
  # scope :not_comp_for_user_buyer, -> (uid) {joins(:job_posting => :user).where("(users.id = ?)", uid).where('buyer_completed = ? OR seller_completed = ?')}
  # scope :not_comp_for_user_seller, -> (uid) {joins(:asking_price => {:skill => :user}).where("(users.id = ?)", uid).where('buyer_completed = "f" OR seller_completed = "f"')}

  #Methods
  def completed?
    self.buyer_completed & self.seller_completed
  end
end

app/controllers/accepted_jobs_controller.rb
class AcceptedJobsController < ApplicationController
  before_action :set_accepted_job, only: [:show, :edit, :update, :destroy]

  # GET /accepted_jobs
  # GET /accepted_jobs.json
  def index
    @accepted_jobs = AcceptedJob.all
    @acc_jobs_buy = AcceptedJob.for_user_buyer(current_user.id)
    @acc_jobs_sell = AcceptedJob.for_user_seller(current_user.id)
  end

  # GET /accepted_jobs/1
  # GET /accepted_jobs/1.json
  def show
  end

  # GET /accepted_jobs/new
  def new
    @accepted_job = AcceptedJob.new
  end

  # GET /accepted_jobs/1/edit
  def edit
  end

  # POST /accepted_jobs
  # POST /accepted_jobs.json
  def create
    @accepted_job = AcceptedJob.new(accepted_job_params)

    respond_to do |format|
      if @accepted_job.save
        format.html { redirect_to @accepted_job, notice: 'Accepted job was successfully created.' }
        format.json { render :show, status: :created, location: @accepted_job }
      else
        format.html { render :new }
        format.json { render json: @accepted_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accepted_jobs/1
  # PATCH/PUT /accepted_jobs/1.json
  def update
    respond_to do |format|
      if @accepted_job.update(accepted_job_params)
        format.html { redirect_to @accepted_job, notice: 'Accepted job was successfully updated.' }
        format.json { render :show, status: :ok, location: @accepted_job }
      else
        format.html { render :edit }
        format.json { render json: @accepted_job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accepted_jobs/1
  # DELETE /accepted_jobs/1.json
  def destroy
    @accepted_job.destroy
    respond_to do |format|
      format.html { redirect_to accepted_jobs_url, notice: 'Accepted job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def initiate_buy
    @jp = JobPosting.find(params[:jp_id])
    @ny_asking_prices = AskingPrice.open_not_for_user(current_user.id)
  end

  def make
    @accepted_job = AcceptedJob.new()
    @accepted_job.job_posting_id = params[:jp_id]
    @accepted_job.asking_price_id = params[:ap_id]

    respond_to do |format|
      if @accepted_job.save
        format.html { redirect_to accepted_jobs_path, notice: 'Accepted job was successfully created.' }
        format.json { render :show, status: :created, location: @accepted_job }
      else
        format.html { render :new }
        format.json { render json: @accepted_job.errors, status: :unprocessable_entity }
      end
    end
  end

  def initiate_sell
    @ap = AskingPrice.find(params[:ap_id])
    @ny_job_postings = JobPosting.open_not_for_user(current_user.id)
  end

  def review_provider
    @aj = AcceptedJob.find(params[:aj_id])
  end

  def review_update_provider
    @aj = AcceptedJob.find(params[:aj_id])
    @aj.seller_review = params[:review]
    @aj.seller_rating = params[:rating]

    respond_to do |format|
      if @aj.save
        format.html { redirect_to accepted_jobs_path, notice: 'Thank you for reviewing your experience With CampusConnect!' }
        format.json { render :show, status: :created, location: @accepted_job }
      else
        format.html { render :new }
        format.json { render json: @accepted_job.errors, status: :unprocessable_entity }
      end
    end
  end

  def review_client
    @aj = AcceptedJob.find(params[:aj_id])
  end

  def review_update_client
    @aj = AcceptedJob.find(params[:aj_id])
    @aj.buyer_review = params[:review]
    @aj.buyer_rating = params[:rating]

    respond_to do |format|
      if @aj.save
        format.html { redirect_to accepted_jobs_path, notice: 'Thank you for reviewing your experience With CampusConnect!' }
        format.json { render :show, status: :created, location: @accepted_job }
      else
        format.html { render :new }
        format.json { render json: @accepted_job.errors, status: :unprocessable_entity }
      end
    end
  end

  def completed_jobs
    acc_job_buy = AcceptedJob.comp_for_user_buyer(current_user.id).to_a
    acc_job_sell = AcceptedJob.comp_for_user_seller(current_user.id).to_a
    @acc_job_comp = acc_job_buy + acc_job_sell
  end

  def active_jobs
    all_buy = AcceptedJob.for_user_buyer(current_user.id).to_a
    all_sell = AcceptedJob.for_user_seller(current_user.id).to_a
    comp_buy = AcceptedJob.comp_for_user_buyer(current_user.id).to_a
    comp_sell = AcceptedJob.comp_for_user_seller(current_user.id).to_a
    active_buy = all_buy - comp_buy
    active_sell = all_sell - comp_sell
    @active_jobs = active_buy + active_sell
  end

  def buyer_complete
    aj = AcceptedJob.find(params[:aj_id])
    aj.buyer_completed = true
    
    respond_to do |format|
      if aj.save
        format.html { redirect_to accepted_jobs_path, notice: 'Thank you for marking the job as completed' }
        format.json { render :show, status: :created, location: @accepted_job }
      else
        format.html { render :new }
        format.json { render json: @accepted_job.errors, status: :unprocessable_entity }
      end
    end

  end

  def seller_complete
    aj = AcceptedJob.find(params[:aj_id])
    aj.seller_completed = true
    
    respond_to do |format|
      if aj.save
        format.html { redirect_to accepted_jobs_path, notice: 'Thank you for marking the job as completed' }
        format.json { render :show, status: :created, location: @accepted_job }
      else
        format.html { render :new }
        format.json { render json: @accepted_job.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accepted_job
      @accepted_job = AcceptedJob.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accepted_job_params
      params.require(:accepted_job).permit(:aj_id, :job_posting_id, :asking_price_id, :buyer_completed, :seller_completed, :seller_review, :buyer_review, :seller_rating, :buyer_rating)
    end
end

app/helpers/accepted_jobs_helper.rb
module AcceptedJobsHelper
end

app/views/accepted_jobs/_form.html.erb
<%= form_for(@accepted_job) do |f| %>
  <% if @accepted_job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accepted_job.errors.count, "error") %> prohibited this accepted_job from being saved:</h2>

      <ul>
      <% @accepted_job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_posting_id %><br>
    <%= f.text_field :job_posting_id %>
  </div>
  <div class="field">
    <%= f.label :asking_price_id %><br>
    <%= f.text_field :asking_price_id %>
  </div>
  <div class="field">
    <%= f.label :buyer_completed %><br>
    <%= f.text_field :buyer_completed %>
  </div>
  <div class="field">
    <%= f.label :seller_completed %><br>
    <%= f.text_field :seller_completed %>
  </div>
  <div class="field">
    <%= f.label :seller_review %><br>
    <%= f.text_area :seller_review %>
  </div>
  <div class="field">
    <%= f.label :buyer_review %><br>
    <%= f.text_area :buyer_review %>
  </div>
  <div class="field">
    <%= f.label :seller_rating %><br>
    <%= f.text_field :seller_rating %>
  </div>
  <div class="field">
    <%= f.label :buyer_rating %><br>
    <%= f.text_field :buyer_rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accepted_jobs/active_jobs.html.erb
<div class="col-xs-12 col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
<center>
  <!-- <p id="notice"><%= notice %></p> -->

  <h1>Active Jobs</h1>

  <table class="table">
    <thead>
      <tr>
        <th><p>Job posting</p></th>
        <th><p>Skill(s) Required</p></th>
        <th><p>Asking price</p></th>
        <!-- <th>Completed</th> -->
        <th><p>Seller review</p></th>
        <th><p>Buyer review</p></th>
        <th><p>Seller rating</p></th>
        <th><p>Buyer rating</p></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @active_jobs.each do |accepted_job| %>
        <tr>
          <td><p><%= accepted_job.job_posting.job_name %></p></td>
          <td><p><%= AskingPrice.find(accepted_job.asking_price_id).skill.skill.to_s %></p></td>
          <td><p><%="$" + AskingPrice.find(accepted_job.asking_price_id).price.to_s %></p></td>
          <!-- <td><%# accepted_job.completed? ? "Yes" : accepted_job.buyer_completed? ? 'Waiting on Seller' : link_to("Mark as Completed",buyer_complete_path) %></td> -->
          <td><p><%= (accepted_job.seller_review == nil or accepted_job.seller_review == "") ? "Not Completed" : "Completed" %></p></td>
          <td><p><%= (accepted_job.buyer_review == nil or accepted_job.buyer_review == "") ? "Not Completed" : "Completed"%></p></td>
          <td><p><%= (accepted_job.seller_rating == nil) ? "Not Completed" : "Completed" %></p></td>
          <td><p><%= (accepted_job.buyer_rating == nil) ? "Not Completed" : "Completed"   %></p></td>
          <% if (accepted_job.completed? == true) & (accepted_job.seller_rating == nil) & (accepted_job.seller_review == nil or accepted_job.seller_review == "") %>
            <td><%# link_to "Review Your Service Provider", review_provider_path(accepted_job) %></td>
          <% end %>
          <% if current_user.role == "admin" %>
            <td><%# link_to 'Show', accepted_job %></td>
            <td><%# link_to 'Edit', edit_accepted_job_path(accepted_job) %></td>
            <td><%# link_to 'Destroy', accepted_job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</center>
</div>

app/views/accepted_jobs/completed_jobs.html.erb
<div class="col-xs-12 col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
<center>
  <!-- <p id="notice"><%= notice %></p> -->

  <h1>Job History</h1>

  <table class="table">
    <thead>
      <tr>
        <th><p>Job posting</p></th>
        <th><p>Skill(s) Required</p></th>
        <th><p>Asking price</p></th>
        <!-- <th>Completed</th> -->
        <th><p>Seller review</p></th>
        <th><p>Buyer review</p></th>
        <th><p>Seller rating</p></th>
        <th><p>Buyer rating</p></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @acc_job_comp.each do |accepted_job| %>
        <tr>
          <td><p><%= accepted_job.job_posting.job_name %></p></td>
          <td><p><%= AskingPrice.find(accepted_job.asking_price_id).skill.skill.to_s %></p></td>
          <td><p><%="$" + AskingPrice.find(accepted_job.asking_price_id).price.to_s %></p></td>
          <!-- <td><%= accepted_job.completed? ? "Yes" : accepted_job.buyer_completed? ? 'Waiting on Seller' : link_to("Mark as Completed",buyer_complete_path) %></td> -->
          <td><p><%= (accepted_job.seller_review == nil or accepted_job.seller_review == "") ? "Not Completed" : "Completed" %></p></td>
          <td><p><%= (accepted_job.buyer_review == nil or accepted_job.buyer_review == "") ? "Not Completed" : "Completed"%></p></td>
          <td><p><%= (accepted_job.seller_rating == nil) ? "Not Completed" : "Completed" %></p></td>
          <td><p><%= (accepted_job.buyer_rating == nil) ? "Not Completed" : "Completed"   %></p></td>
          <% if (accepted_job.completed? == true) & (accepted_job.seller_rating == nil) & (accepted_job.seller_review == nil or accepted_job.seller_review == "") %>
            <td><%# link_to "Review Your Service Provider", review_provider_path(accepted_job) %></td>
          <% end %>
          <% if current_user.role == "admin" %>
            <td><%# link_to 'Show', accepted_job %></td>
            <td><%# link_to 'Edit', edit_accepted_job_path(accepted_job) %></td>
            <td><%# link_to 'Destroy', accepted_job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</center>
</div>

app/views/accepted_jobs/edit.html.erb
<h1>Editing Accepted Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @accepted_job %> |
<%= link_to 'Back', accepted_jobs_path %>

app/views/accepted_jobs/index.html.erb
<div class="col-xs-12 col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
<center>
  <!-- <p id="notice"><%= notice %></p> -->
  
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#jobcreate" aria-controls="home" role="tab" data-toggle="tab"><p><b>Jobs Created</b></p></a></li>
    <li role="presentation"><a href="#jobaccept" aria-controls="profile" role="tab" data-toggle="tab"><p><b>Jobs Accepted</b></p></a></li>
  </ul>

  </center>
    <div class="dropdown">
  <button id="dLabel" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Sort
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dLabel">
    <li><a href="#">Most Recent</a></li>
    <li><a href="#">Highest Price</a></li>
    <li><a href="#">Lowest Price</a></li>
    <li><a href="#">Rating</a></li>
  </ul>
</div>
<center>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane active" id="jobcreate">

  <table class="table">
    <thead>
      <tr>
        <th><p>Job posting</p></th>
        <th><p>Skill(s) Required</p></th>
        <th><p>Asking price</p></th>
        <th><p>Completed</p></th>
        <th><p>Review/Rating of Seller</p></th>
        <th><p>Review/Rating of Buyer</p></th>
        <th><p>Job Details</p></th>
        <th><p>Review</p></th>
        <!-- <th><p>Seller rating</p></th> -->
        <!-- <th><p>Buyer rating</p></th> -->
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @acc_jobs_buy.each do |accepted_job| %>
        <tr>
          <td><p><%= accepted_job.job_posting.job_name %></p></td>
          <td><p><%= AskingPrice.find(accepted_job.asking_price_id).skill.skill.to_s %></p></td>
          <td><p><%=AskingPrice.find(accepted_job.asking_price_id).price.to_s %></p></td>
          <td><p><%= accepted_job.completed? ? "Yes" : accepted_job.buyer_completed? ? 'Waiting on Seller' : link_to("Mark as Completed",buyer_complete_path(accepted_job)) %></p></td>
          <td><p><%= (accepted_job.seller_review == nil or accepted_job.seller_review == "" or (accepted_job.seller_rating == nil)) ? "Not Completed" : "Completed" %></p></td>
          <td><p><%= (accepted_job.buyer_review == nil or accepted_job.buyer_review == "" or (accepted_job.buyer_rating == nil)) ? "Not Completed" : "Completed"%></p></td>
          <!-- <td><p><%# (accepted_job.seller_rating == nil) ? "Not Completed" : "Completed" %></p></td> -->
          <!-- <td><p><%# (accepted_job.buyer_rating == nil) ? "Not Completed" : "Completed"   %></p></td> -->
          <td><p><%= link_to 'View Job', accepted_job, class: "btn btn-info" %></p></td>
          <% if (accepted_job.completed? == true) & (accepted_job.seller_rating == nil) & (accepted_job.seller_review == nil or accepted_job.seller_review == "") %>
            <td><p><%= link_to "Review Your Service Provider", review_provider_path(accepted_job) %></p></td>
          <% end %>
          <% if current_user.role == "admin" %>
            <td><%= link_to 'View Job', accepted_job, class: "btn btn-success" %></td>
            <td><%= link_to 'Edit', edit_accepted_job_path(accepted_job), class: "btn btn-warning" %></td>
            <td><%= link_to 'Cancel Job', accepted_job, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>



<div role="tabpanel" class="tab-pane" id="jobaccept">

  <table class="table">
    <thead>
      <tr>
        <th><p>Job posting</p></th>
        <th><p>Skill(s) Required</p></th>
        <th><p>Asking price</p></th>
        <th><p>Completed</p></th>
        <th><p>Review/Rating of Seller</p></th>
        <th><p>Review/Rating of Buyer</p></th>
        <th><p>Job Details</p></th>
        <th><p>Review</p></th>
        <!-- <th><p>Seller rating</p></th> -->
        <!-- <th><p>Buyer rating</p></th> -->
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @acc_jobs_sell.each do |accepted_job| %>
        <tr>
          <td><p><%= accepted_job.job_posting.job_name %></p></td>
          <td><p><%= AskingPrice.find(accepted_job.asking_price_id).skill.skill.to_s %></p></td>
          <td><p><%= AskingPrice.find(accepted_job.asking_price_id).price.to_s %></p></td>
          <td><p><%= accepted_job.completed? ? "Yes" : accepted_job.seller_completed? ? 'Waiting on Buyer' : link_to("Mark as Completed",seller_complete_path(accepted_job)) %></p></td>
          <td><p><%= (accepted_job.seller_review == nil or accepted_job.seller_review == "" or (accepted_job.seller_rating == nil)) ? "Not Completed" : "Completed" %></p></td>
          <td><p><%= (accepted_job.buyer_review == nil or accepted_job.buyer_review == "" or (accepted_job.buyer_rating == nil)) ? "Not Completed" : "Completed"%></p></td>
          <!-- <td><p><%# (accepted_job.seller_rating == nil) ? "Not Completed" : "Completed" %></p></td> -->
          <!-- <td><p><%# (accepted_job.buyer_rating == nil) ? "Not Completed" : "Completed"   %></p></td> -->
          <td><p><%= link_to 'View Job', accepted_job, class: "btn btn-info" %></p></td>
          <% if (accepted_job.completed? == true) & (accepted_job.buyer_rating == nil) & (accepted_job.buyer_review == nil or accepted_job.buyer_review == "") %>
            <td><p><%= link_to "Review Your Service Provider", review_client_path(accepted_job) %></p></td>
          <% end %>
          <% if current_user.role == "admin" %>
            <td><%= link_to 'View Job', accepted_job, class: "btn btn-success" %></td>
            <td><%= link_to 'Edit', edit_accepted_job_path(accepted_job), class: "btn btn-warning" %></td>
            <td><%= link_to 'Cancel Job', accepted_job, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  </div>
</div>
</center>
</div>

app/views/accepted_jobs/initiate_buy.html.erb
<div class="col-xs-12 col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
<center>

<h1>Here are the current job offerings</h1>
<br>
<table class="table">
  <thead>
    <tr>
      <!-- <th>Buyer</th> -->
      <th><p>Skill Offered</p></th>
      <th><p>Description</p></th>
      <th><p>Price</p></th>
      <th><p>Quantity</p></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ny_asking_prices.each do |ap| %>
      <tr>
        <!-- <td><%# job_posting.buyer_id %></td> -->
        <td><p><%= ap.skill.skill %></p></td>
        <td><p><%= ap.skill.description %></p></td>
        <td><p><%= ap.price %></p></td>
        <td><p><%= ap.quantity %></p></td>
        <td><%= link_to 'Select Job Offering', make_accepted_job_path(@jp,ap), class: "btn btn-primary btn-sm"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>

<br>
<br>
<br>
<br>
<br>

<i>
<h4><b>Your Needed Job</b></h4>
<p><%= "Name: " + (@jp.job_name === "" ? "No Name" : @jp.job_name) %></p><br>
<p><%= "Description: " + (@jp.description === "" ? "No description" : @jp.description) %></p><br>
<p><%= "Skills Required: " + (@jp.skills_required === "" ? "No skills required" : @jp.skills_required) %></p><br>
<p><%= "Estimated Time Required: " + (@jp.estimated_time === "" ? "No Estimated Time Required" : @jp.estimated_time) %></p><br>
</i>

</div>

app/views/accepted_jobs/new.html.erb
<h1>New Accepted Job</h1>

<%= render 'form' %>

<%= link_to 'Back', accepted_jobs_path %>

app/views/accepted_jobs/review_client.html.erb
<center>
  <h4>Please review your client<!-- , Username: <i><%= @aj.asking_price.skill.user.username %></i> --></h4>
  <br><br>

<div class="row">
<div class="col-md-4 col-md-offset-4">
  <center>
    <h2> Hi! How was working with <br> </h2>
    <h3><%= @aj.job_posting.user.name %></h3>
    
    <img src="<%=image_path "bearded-man.jpg"%>"  width=100 height=120>
    <br>
  </center>

  <%= form_tag(review_update_client_path, :method => "post") do %>
  <div class="form-group"> 
      <%= label_tag(:review, "Review") %>
      <%= text_area_tag :review, nil, rows: 5, cols: 25, class:"form-control"  %><br>
  </div>

  <div class="form-group"> 
      <%= label_tag(:rating, "Rating (From 1 to 5)" ) %>
      <%= number_field_tag :rating, 4, within: 1...6 , class:"form-control" %><br>
  </div>


  <%= submit_tag("Submit Review", :class=>"form-control") %>
  <br><br><br>
<% end %>

  
</div>
</div>

app/views/accepted_jobs/review_provider.html.erb
<center>
  <h4>Please review the provider of your service<!-- , Username: <i><%= @aj.asking_price.skill.user.username %></i> --></h4>
  <br><br>

<div class="row">
<div class="col-md-4 col-md-offset-4">
  <center>
    <h2> Hi! How was working with <br> </h2>
    <h3><%= @aj.asking_price.skill.user.name %></h3>
    
    <img src="<%=image_path "bearded-man.jpg"%>"  width=100 height=120>
    <br>
  </center>

  <%= form_tag(review_update_provider_path, :method => "post") do %>
  <div class="form-group"> 
      <%= label_tag(:review, "Review") %>
      <%= text_area_tag :review, nil, rows: 5, cols: 25, class:"form-control"  %><br>
  </div>

  <div class="form-group"> 
      <%= label_tag(:rating, "Rating (From 1 to 5)" ) %>
      <%= number_field_tag :rating, 4, within: 1...6 , class:"form-control" %><br>
  </div>


  <%= submit_tag("Submit Review", :class=>"form-control") %>
  <br><br><br>
<% end %>

  
</div>
</div>